spring:
  application:
    name: 'sige'
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    password: Brasilangola@2310
    tomcat:
      max-active: '50'
      max-idle: '20'
      max-wait: '20000'
      min-idle: '15'
    url: jdbc:sqlserver://172.16.10.216:1433;databaseName=siga_okayula_cgs
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format_sql: 'true  '
        id:
          new_generator_mappings: 'false '
    show-sql: false
 
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
